### ISSUE TITLE
Authentication Header Error

### ISSUE THREAD

**Issue by N3rdP1um23** [sebdesign/artisan-cloudflare#10]
I find that I cannot use X-Auth-Key when making a request and get a response of `6003: Invalid request headers` if I do.  I played around and, if I replace it with `Authorization` as the header key and `Bearer [API TOKEN]` as the value, the request is successful with Cloudflare.

I Just wanted to add this in as an issue to see about getting it resolved.  I can make a PR if needed

**Comment by sebdesign** [comment]
Hi, I didn't know you could use API tokens instead of API keys. Thanks for letting me know!

I've implemented this in the v2.1.0 release. Please update your dependencies and let me know if it works. 

Fixed in 98ffd151035f1ea210e06ce1062f6015b44ed13b.

**Comment by N3rdP1um23** [comment]
Thank you!  And no worries, I was trying your package and chouldn't get it working with the key and email.  After a little bit and looking at different examples, I tried that and it worked successfully.  I then tried locally editing your ServiceProvider.php file and it worked.

Thought I'd let ya know :)

Yes, I have updated and verified that everything is working successfully!
