### ISSUE TITLE
Output error when running commands programmatically 

### ISSUE THREAD

**Issue by amorphia** [sebdesign/artisan-cloudflare#12]
When attempting to run the purge commands programmatically as part of a controller action using:

`Artisan::call('cloudflare:cache:purge' );`

I'm getting the following error:

`PHP Error:  Call to undefined method Symfony/Component/Console/Output/BufferedOutput::section() in [MY_PATH]/vendor/laravel/framework/src/Illuminate/Console/Concerns/InteractsWithIO.php on line 225`

Commenting out line 88 in Purge.php:

`$this->displayResults($zones, $results);`

Prevents this error. 

Would it be possible to get a flag we can set for a "silent" mode that would omit displaying results to sidestep this issue?

**Comment by sebdesign** [comment]
I think Symfony can disable output using the `--quiet` flag.
Can you try calling `Artisan::call('cloudflare:cache:purge', ['--quiet'])`?

**Comment by amorphia** [comment]
Ah, embarrassing. I tried to suppress it using the -q flag instead of --quiet but that had failed, this seemed to work without issue. Thanks much!
