### ISSUE TITLE
error composer installing (array of null)

### ISSUE THREAD

**Issue by idmahbub** [sebdesign/artisan-cloudflare#14]
<img width="516" alt="Screenshot 2020-07-21 at 10 06 27 AM" src="https://user-images.githubusercontent.com/2823242/88008194-ef80ee00-cb39-11ea-90d2-0780b235f469.png">

Php v.7.4
Laravel ^7.0

**Comment by sebdesign** [comment]
Did you publish the config file? (`php artisan vendor:publish`).
I cannot understand the error from you screenshot, could you please copy-paste the exception stack trace?

**Comment by sebdesign** [comment]
Hello, did you manage to install this package?

**Comment by dellow** [comment]
I'm also having this problem. This is happens when installing via composer and during the package:discover phase so before you get a chance the publish the config file.

As composer detects an error it reverts composer.json back to normal therefore the package fails to install.
