### ISSUE TITLE
PHP 8 Support

### ISSUE THREAD

**Issue by olipayne** [sebdesign/artisan-cloudflare#15]
Hello! On a ```composer update``` when running PHP 8, this is one of the packages which fails:

```  Problem 2
    - sebdesign/artisan-cloudflare[v2.4.0, ..., v2.4.1] require php ^7.1 -> your php version (8.0.0) does not satisfy that requirement.
    - Root composer.json requires sebdesign/artisan-cloudflare ^2.4 -> satisfiable by sebdesign/artisan-cloudflare[v2.4.0, v2.4.1].```

**Comment by sebdesign** [comment]
Hello!

I've tagged v2.4.2 that adds support for PHP 8. I haven't tested it yet and Travis CI is not working so let me know if it doesn't work.

**Comment by neochief** [comment]
In my project PHP8-wise, everything works fine. However, there seem to be a few unrelated issues that already fixed in master, but not present in the latest release tag. Could you please make a fresh tag?

**Comment by sebdesign** [comment]
@neochief it seems I forgot to tag it! Here is v2.4.3.
