### ISSUE TITLE
10000: Authentication error

### ISSUE THREAD

**Issue by caocanhlinh** [sebdesign/artisan-cloudflare#16]
I have an Authentication error, even though I have filled in the information in the config/cloudflare file.
![Screenshot 2020-12-09 000639](https://user-images.githubusercontent.com/44583838/101516827-90215e80-39b2-11eb-8d0d-f76126438f8d.png)

**Comment by sebdesign** [comment]
Hello, did you find a solution for the authentication error?

**Comment by caocanhlinh** [comment]
Hi, Thanks for your feedback. Maybe the fault is with me. 
I changed from 
-------------------------------------------------
    'token' => env('CLOUDFLARE_TOKEN'),

    'key' => env('CLOUDFLARE_KEY'),

    'email' => env('CLOUDFLARE_EMAIL'),
--------------------------------------------------
to 
-------------------------------------------------
    'token' => 'CLOUDFLARE_TOKEN',

    'key' => 'CLOUDFLARE_KEY',

    'email' => 'CLOUDFLARE_EMAIL',
--------------------------------------------------

**Comment by sebdesign** [comment]
You need to set the token (or the key and the email) to your `.env` file, not in the `config/cloudflare.php` file.

**Comment by caocanhlinh** [comment]
Yep!! I forgot. Thanks
