### ISSUE TITLE
Unresolvable dependency resolving

### ISSUE THREAD

**Issue by caocanhlinh** [sebdesign/artisan-cloudflare#17]
hello!! I got the above error when used in conjunction with task scheduling.

`Unresolvable dependency resolving [Parameter #0 [ <required> array $zones ]] in class App\Console\Commands\Purge`

![image](https://user-images.githubusercontent.com/44583838/102230031-f829f480-3f1e-11eb-8c2a-518b40610f00.png)

**Comment by sebdesign** [comment]
Hello!

Which version are you using?
Have you published the `cloudflare.php` config file?

**Comment by sebdesign** [comment]
Also, is `App\Console\Commands\Purge` extending `Sebdesign\ArtisanCloudflare\Commands\Cache\Purge`?

**Comment by caocanhlinh** [comment]
I have published cloudflare.php configuration file

I run the console command fine. but with task scheduling, there's an error.

`Also, is App\Console\Commands\Purge extending Sebdesign\ArtisanCloudflare\Commands\Cache\Purge?`
Yep

**Comment by sebdesign** [comment]
Ok, the issue is the extended class.

The `Purge` command from this package is registered in the service provider, and accepts the zones from the config: https://github.com/sebdesign/artisan-cloudflare/blob/master/src/ServiceProvider.php#L61

In order to extend this class there are two solutions:

#### 1. Bind it to the container in the same manner:
```php
$this->app->bind(\App\Console\Commands\Cache\Purge::class, function ($app) {
    return new \App\Console\Commands\Cache\Purge(
        $app['config']['cloudflare.zones'] ?? []
    );
});
```

#### 2. Or pass the zones from the config to the parent constructor of you extended class:

```php
public function __construct()
{
    parent::__construct(config('cloudflare.zones'));
}
```

**Comment by caocanhlinh** [comment]
I tried the above 2 solutions but still got the error.

**Comment by sebdesign** [comment]
Can you show me the full stack trace and your class?

**Comment by caocanhlinh** [comment]
> #### 1. Bind it to the container in the same manner:
> ```
> $this->app->bind(\App\Console\Commands\Cache\Purge::class, function ($app) {
>     return new \App\Console\Commands\Cache\Purge(
>         $app['config']['cloudflare.zones'] ?? []
>     );
> });
> ```

```
$this->app->bind(\App\Console\Commands\Cache\Purge::class, function ($app) {
    return new \App\Console\Commands\Cache\Purge(
        $app['config']['cloudflare.zones'] ?? []
    );
});

  $this->commands([
      \App\Console\Commands\Cache\Purge::class,
  ]);
```
It worked. Thank you so much
