### ISSUE TITLE
Return type of Sebdesign\ArtisanCloudflare\Zone::jsonSerialize() -> php 8.1 warning

### ISSUE THREAD

**Issue by vesper8** [sebdesign/artisan-cloudflare#21]
Hi there, love your package by the way, thanks for making it.

I've noticed that since upgrading to php 8.1 I get this warning

```

Return type of Sebdesign\ArtisanCloudflare\Zone::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /vendor/sebdesign/artisan-cloudflare/src/Zone.php on line 22
```

It's just a warning for now, but will probably become more of an issue in future version of PHP. It would be nice if you could resolve it.

Many thanks!

**Comment by sebdesign** [comment]
Thank you for the heads up! I will fix it today.
