### ISSUE TITLE
laravel 5.6 support?

### ISSUE THREAD

**Issue by maorkavod** [sebdesign/artisan-cloudflare#6]
will it have a laravel 5.6 support any time soon?

**Comment by sebdesign** [comment]
I will add support for laravel 5.6 in the next few days (if not today).

**Comment by maorkavod** [comment]
Thank you very much :)
this is an awesome package!

**Comment by sebdesign** [comment]
I've tagged a new release for Laravel 5.6.

https://github.com/sebdesign/artisan-cloudflare/releases/tag/v1.2.0

**Comment by maorkavod** [comment]
thank you!
