### ISSUE TITLE
Undefined property: stdClass::$code

### ISSUE THREAD

**Issue by juanhuerta** [sebdesign/artisan-cloudflare#7]
Hi! great work!

I just installed the last version of your plugin 1.2.0 in a dev environment with no problems, I tested and everything went ok, but after doing the same steps in the production server, same config, keys, zones, etc., when I try to do a cache:purge I see:
"In Purge.php line 221:
  Undefined property: stdClass::$code"

The production server is a clone of the dev one, any idea what's happening? Thanks

**Comment by sebdesign** [comment]
Hi @juanhuerta,

I haven't encountered this error before. Can you check your laravel logs for other errors just before the error on Purge.php line 221? The http client that connects to CloudFlare has a logger attached, so you might find some useful information there. Can you post it here please?

**Comment by juanhuerta** [comment]
I use guzzlehttp/guzzle and I can't find any guzzle log. Here is the complete laravel log:

[2018-07-30 09:45:08] production.ERROR: Undefined property: stdClass::$code {"exception":"[object] (ErrorException(code: 0): Undefined property: stdClass::$code at /laravel/vendor/sebdesign/artisan-cloudflare/src/Commands/Cache/Purge.php:221)
[stacktrace]
#0 /laravel/vendor/sebdesign/artisan-cloudflare/src/Commands/Cache/Purge.php(221): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Undefined prope...', '/laravel/ven...', 221, Array)
#1 [internal function]: Sebdesign\\ArtisanCloudflare\\Commands\\Cache\\Purge->Sebdesign\\ArtisanCloudflare\\Commands\\Cache\\{closure}(Object(stdClass))
#2 /laravel/vendor/sebdesign/artisan-cloudflare/src/Commands/Cache/Purge.php(226): array_map(Object(Closure), Array)
#3 /laravel/vendor/sebdesign/artisan-cloudflare/src/Commands/Cache/Purge.php(182): Sebdesign\\ArtisanCloudflare\\Commands\\Cache\\Purge->formatErrors(Array)
#4 [internal function]: Sebdesign\\ArtisanCloudflare\\Commands\\Cache\\Purge->Sebdesign\\ArtisanCloudflare\\Commands\\Cache\\{closure}(Object(stdClass), '5ce63c34e623915...')
#5 /laravel/vendor/laravel/framework/src/Illuminate/Support/Collection.php(861): array_map(Object(Closure), Array, Array)
#6 /laravel/vendor/sebdesign/artisan-cloudflare/src/Commands/Cache/Purge.php(183): Illuminate\\Support\\Collection->map(Object(Closure))
#7 /laravel/vendor/sebdesign/artisan-cloudflare/src/Commands/Cache/Purge.php(88): Sebdesign\\ArtisanCloudflare\\Commands\\Cache\\Purge->displayResults(Object(Illuminate\\Support\\Collection), Object(Illuminate\\Support\\Collection))
#8 [internal function]: Sebdesign\\ArtisanCloudflare\\Commands\\Cache\\Purge->handle()
#9 /laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#10 /laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#11 /laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#12 /laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#13 /laravel/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#14 /laravel/vendor/symfony/console/Command/Command.php(251): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#15 /laravel/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#16 /laravel/vendor/symfony/console/Application.php(946): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#17 /laravel/vendor/symfony/console/Application.php(248): Symfony\\Component\\Console\\Application->doRunCommand(Object(Sebdesign\\ArtisanCloudflare\\Commands\\Cache\\Purge), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#18 /laravel/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#19 /laravel/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#20 /laravel/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#21 /laravel/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#22 {main}
"}

**Comment by juanhuerta** [comment]
I found more log info:

`[2018-07-30 09:45:08] production.ERROR: Client error: `DELETE https://api.cloudflare.com/client/v4/zones/5ce63c34e62391552008d7.../purge_cache` resulted in a `426 Upgrade Required` response:
{"success":false,"errors":[{"yourTlsVersion":"TLSv1", "message":"Cloudflare does not support deprecated TLS versions for (truncated...)
 {"zone":"5ce63c34e62391552008d7...","exception":"[object] (GuzzleHttp\\Exception\\ClientException(code: 426): Client error: `DELETE https://api.cloudflare.com/client/v4/zones/5ce63c34e62391552008d7.../purge_cache` resulted in a `426 Upgrade Required` response:
{\"success\":false,\"errors\":[{\"yourTlsVersion\":\"TLSv1\", \"message\":\"Cloudflare does not support deprecated TLS versions for (truncated...)
 at /laravel/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113)
[stacktrace]`

**Comment by sebdesign** [comment]
I have identified the bug that caused the error. In your latest comment, it seems that the CloudFlare API doesn't return a `code` property, and I didn't properly check for that case. This has been fixed in v1.2.1. Please update and let me know if that fixes the error.

But the real issue is that cURL is using TLSv1 on your server, which is outdated and not supported by CloudFlare anymore. You need to have TLS 1.2, so please check your server specifications (PHP, cURL, etc. In the next release I will force Guzzle to use TLSv1.2, which might help.

Also see https://stackoverflow.com/a/33134596/935726 for more info.

Cheers!

**Comment by juanhuerta** [comment]
You were right, I had been using an old version of Curl. After updating to Curl 7.61.0 now I can talk to Cloudflare.

BTW, after updating your package the output changed to a readable cloudflare error indicating that it is needed TLS 1.2

Thanks for your help!

**Comment by sebdesign** [comment]
Glad to help! :)
